name: health
description: Wrapper for Apple's HealthKit on iOS and Google's Health Connect on Android.
version: 13.2.0-mindfulness.1
homepage: https://github.com/cph-cachet/flutter-plugins/tree/master/packages/health

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.6.0"

dependencies:
  flutter:
    sdk: flutter
  intl: '>=0.18.0 <0.21.0'
  device_info_plus: '^12.1.0'
  json_annotation: ^4.9.0
  carp_serializable: ^2.0.1 # polymorphic json serialization

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: any

  # Using carp_serializable & json_serializable to auto generate json code (.g files) with this command:
  #   dart run build_runner build --delete-conflicting-outputs
  build_runner: any
  json_serializable: any
  mocktail: ^1.0.4
  mockito: ^5.4.5

flutter:
  plugin:
    platforms:
      android:
        package: cachet.plugins.health
        pluginClass: HealthPlugin
      ios:
        pluginClass: HealthPlugin
